# Generated by Django 3.1 on 2020-08-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
