# Generated by Django 3.1 on 2020-08-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(to='app.Genre'),
        ),
    ]
