# Generated by Django 3.0.7 on 2020-08-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200814_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
